#!/usr/bin/env python3
"""Analyze expert audit results by unblinding hypotheses and comparing Unbox vs SCAM.

The expert_audit.json contains 12 evaluations from the Unbox pipeline.
The audit_blinded_set.json contains 6 Unbox + 6 SCAM hypotheses for comparison.
6 Unbox hypotheses match exactly between both files; the 6 SCAM hypotheses
in the blinded set were not evaluated in the expert audit (they are different
hypotheses generated by SCAM). The remaining 6 audit evaluations are additional
Unbox hypotheses not included in the blinded set.

This script:
  1. Matches the 6 Unbox hypotheses between blinded set and audit (by text).
  2. Reports scores for matched Unbox hypotheses (with blinded IDs).
  3. Reports scores for the 6 additional Unbox hypotheses in the audit.
  4. Notes that SCAM hypotheses lack expert audit scores.
  5. Compares the 6 "selected" Unbox hypotheses vs the 6 "additional" Unbox
     hypotheses as a within-system analysis.
"""

import json
import math
import os
from datetime import datetime, timezone

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIT_PATH = os.path.join(BASE_DIR, "experiments", "prospective", "expert_audit.json")
BLINDED_PATH = os.path.join(BASE_DIR, "experiments", "prospective", "audit_blinded_set.json")
OUTPUT_PATH = os.path.join(BASE_DIR, "evidence", "expert_audit_analysis.json")

METRICS = ["novelty", "feasibility", "impact", "clarity", "composite"]


def load_json(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


def normalize_text(s: str) -> str:
    return " ".join(s.strip().split()).lower()


def mann_whitney_u(x: list, y: list) -> dict:
    """Mann-Whitney U with normal approximation. Returns U, z, p (two-sided)."""
    n1, n2 = len(x), len(y)
    if n1 == 0 or n2 == 0:
        return {"U": None, "z": None, "p": None}

    pooled = [(v, 0) for v in x] + [(v, 1) for v in y]
    pooled.sort(key=lambda t: t[0])

    ranks = [0.0] * len(pooled)
    i = 0
    while i < len(pooled):
        j = i
        while j < len(pooled) and pooled[j][0] == pooled[i][0]:
            j += 1
        avg_rank = (i + j + 1) / 2.0
        for k in range(i, j):
            ranks[k] = avg_rank
        i = j

    R1 = sum(ranks[k] for k in range(len(pooled)) if pooled[k][1] == 0)
    U1 = R1 - n1 * (n1 + 1) / 2.0
    U = min(U1, n1 * n2 - U1)

    mu = n1 * n2 / 2.0
    n = n1 + n2
    tie_counts = []
    i = 0
    while i < len(pooled):
        j = i
        while j < len(pooled) and pooled[j][0] == pooled[i][0]:
            j += 1
        if j - i > 1:
            tie_counts.append(j - i)
        i = j

    tie_corr = sum(t ** 3 - t for t in tie_counts)
    denom = n1 * n2 / 12.0 * ((n + 1) - tie_corr / (n * (n - 1))) if n > 1 else 0
    sigma = math.sqrt(denom) if denom > 0 else 0

    if sigma == 0:
        return {"U": float(U), "z": 0.0, "p": 1.0}

    z = (U1 - mu) / sigma
    p = 2.0 * _norm_cdf(-abs(z))
    return {"U": float(U), "z": round(z, 4), "p": round(p, 4)}


def _norm_cdf(x: float) -> float:
    return 0.5 * (1.0 + _erf(x / math.sqrt(2.0)))


def _erf(x: float) -> float:
    sign = 1 if x >= 0 else -1
    x = abs(x)
    t = 1.0 / (1.0 + 0.3275911 * x)
    y = 1.0 - (
        ((((1.061405429 * t - 1.453152027) * t) + 1.421413741) * t - 0.284496736) * t
        + 0.254829592
    ) * t * math.exp(-x * x)
    return sign * y


def mean(values: list) -> float:
    return sum(values) / len(values) if values else 0.0


def compute_avg(score_dicts: list) -> dict:
    """Compute average across a list of score dicts (each has metric keys)."""
    result = {}
    for metric in METRICS:
        values = [s[metric] for s in score_dicts if metric in s and s[metric] is not None]
        result[metric] = round(mean(values), 3) if values else None
    return result


def main():
    audit = load_json(AUDIT_PATH)
    blinded = load_json(BLINDED_PATH)

    unblinding_key = blinded["_unblinding_key"]
    blinded_hyps = blinded["hypotheses"]

    # Classify blinded hypotheses by system
    unbox_ids = sorted([h["id"] for h in blinded_hyps if unblinding_key[h["id"]]["system"] == "unbox"])
    scam_ids = sorted([h["id"] for h in blinded_hyps if unblinding_key[h["id"]]["system"] == "scam"])

    # Build text index from blinded set
    text_to_blinded = {}
    for h in blinded_hyps:
        text_to_blinded[normalize_text(h["hypothesis"])] = h

    # Match audit evaluations to blinded hypothesis IDs
    matched_unbox = []  # Unbox hypotheses in both blinded set and audit
    extra_unbox = []    # Audit evals not in blinded set (additional Unbox)
    audit_used = set()

    for i, ev in enumerate(audit["evaluations"]):
        norm = normalize_text(ev["hypothesis"])
        bh = text_to_blinded.get(norm)
        if bh:
            hid = bh["id"]
            system = unblinding_key[hid]["system"]
            matched_unbox.append({
                "id": hid,
                "system": system,
                "paradigm": ev["paradigm"],
                "transformation": unblinding_key[hid]["transformation"],
                "hypothesis": ev["hypothesis"],
                "avg_scores": ev["avg_scores"],
                "per_judge": ev.get("per_judge"),
            })
            audit_used.add(i)
        else:
            extra_unbox.append({
                "audit_index": i,
                "paradigm": ev["paradigm"],
                "hypothesis": ev["hypothesis"],
                "avg_scores": ev["avg_scores"],
            })

    # SCAM hypotheses from blinded set (no audit scores)
    scam_blinded = []
    for h in blinded_hyps:
        if unblinding_key[h["id"]]["system"] == "scam":
            scam_blinded.append({
                "id": h["id"],
                "system": "scam",
                "paradigm": h["paradigm"],
                "transformation": unblinding_key[h["id"]]["transformation"],
                "hypothesis": h["hypothesis"],
                "avg_scores": None,  # Not evaluated in expert audit
            })

    print(f"Matched Unbox hypotheses (in both blinded set and audit): {len(matched_unbox)}")
    print(f"  IDs: {[m['id'] for m in matched_unbox]}")
    print(f"Additional Unbox hypotheses (in audit only): {len(extra_unbox)}")
    print(f"SCAM hypotheses (in blinded set only, no audit scores): {len(scam_blinded)}")
    print(f"  IDs: {[s['id'] for s in scam_blinded]}")

    # ---- Unbox scores (from matched blinded hypotheses) ----
    unbox_scores = [m["avg_scores"] for m in matched_unbox]
    unbox_avg = compute_avg(unbox_scores)

    # ---- Additional Unbox scores (not in blinded set) ----
    extra_scores = [e["avg_scores"] for e in extra_unbox]
    extra_avg = compute_avg(extra_scores)

    # ---- All 12 audit evals (all Unbox pipeline) ----
    all_audit_scores = [e["avg_scores"] for e in audit["evaluations"]]
    all_audit_avg = compute_avg(all_audit_scores)

    # ---- Compare selected vs additional Unbox ----
    print(f"\n{'Metric':<12} {'Selected(6)':>12} {'Additional(6)':>14} {'All(12)':>10}")
    print("-" * 52)
    for m in METRICS:
        sel = unbox_avg[m] if unbox_avg[m] is not None else 0
        ext = extra_avg[m] if extra_avg[m] is not None else 0
        tot = all_audit_avg[m] if all_audit_avg[m] is not None else 0
        print(f"{m:<12} {sel:>12.3f} {ext:>14.3f} {tot:>10.3f}")

    # Mann-Whitney: selected Unbox (6) vs additional Unbox (6)
    print("\nMann-Whitney U: Selected Unbox (blinded) vs Additional Unbox")
    mw_selected_vs_extra = {}
    for metric in METRICS:
        x = [s[metric] for s in unbox_scores if metric in s]
        y = [s[metric] for s in extra_scores if metric in s]
        result = mann_whitney_u(x, y)
        mw_selected_vs_extra[metric] = result
        print(f"  {metric}: U={result['U']}, z={result['z']}, p={result['p']}")

    # ---- Per-hypothesis table ----
    per_hypothesis = []
    for m in matched_unbox:
        entry = {
            "id": m["id"],
            "system": m["system"],
            "paradigm": m["paradigm"],
            "transformation": m["transformation"],
            "hypothesis_snippet": m["hypothesis"][:100],
            "has_audit_scores": True,
        }
        entry.update({metric: m["avg_scores"].get(metric) for metric in METRICS})
        per_hypothesis.append(entry)

    for s in scam_blinded:
        entry = {
            "id": s["id"],
            "system": "scam",
            "paradigm": s["paradigm"],
            "transformation": s["transformation"],
            "hypothesis_snippet": s["hypothesis"][:100],
            "has_audit_scores": False,
        }
        entry.update({metric: None for metric in METRICS})
        per_hypothesis.append(entry)

    per_hypothesis.sort(key=lambda e: e["id"])

    print(f"\n{'ID':<5} {'System':<7} {'Paradigm':<22} {'Nov':>5} {'Feas':>5} {'Imp':>5} {'Clar':>5} {'Comp':>5}")
    print("-" * 70)
    for h in per_hypothesis:
        if h["has_audit_scores"]:
            print(f"{h['id']:<5} {h['system']:<7} {h['paradigm']:<22} "
                  f"{h['novelty']:>5.1f} {h['feasibility']:>5.1f} {h['impact']:>5.1f} "
                  f"{h['clarity']:>5.1f} {h['composite']:>5.1f}")
        else:
            print(f"{h['id']:<5} {h['system']:<7} {h['paradigm']:<22}   N/A   N/A   N/A   N/A   N/A")

    # ---- Additional Unbox hypothesis details ----
    extra_per_hypothesis = []
    for e in extra_unbox:
        entry = {
            "audit_index": e["audit_index"],
            "paradigm": e["paradigm"],
            "hypothesis_snippet": e["hypothesis"][:100],
        }
        entry.update({metric: e["avg_scores"].get(metric) for metric in METRICS})
        extra_per_hypothesis.append(entry)

    print(f"\nAdditional Unbox hypotheses (in audit, not in blinded set):")
    for h in extra_per_hypothesis:
        print(f"  audit[{h['audit_index']}] {h['paradigm']:<22} "
              f"Nov={h['novelty']:.1f} Feas={h['feasibility']:.1f} "
              f"Imp={h['impact']:.1f} Comp={h['composite']:.1f}")

    # ---- Per-paradigm breakdown (Unbox selected only) ----
    paradigms = sorted(set(m["paradigm"] for m in matched_unbox))
    per_paradigm = {}
    for p in paradigms:
        p_evals = [m["avg_scores"] for m in matched_unbox if m["paradigm"] == p]
        per_paradigm[p] = {
            "count": len(p_evals),
            "avg": compute_avg(p_evals),
        }
        # Also include extra Unbox for this paradigm
        p_extra = [e["avg_scores"] for e in extra_unbox if e["paradigm"] == p]
        if p_extra:
            per_paradigm[p]["extra_count"] = len(p_extra)
            per_paradigm[p]["extra_avg"] = compute_avg(p_extra)

    print("\nPer-paradigm breakdown (selected Unbox):")
    for p, info in per_paradigm.items():
        print(f"  {p} (n={info['count']}): composite={info['avg']['composite']}")
        if "extra_avg" in info:
            print(f"    + extra (n={info['extra_count']}): composite={info['extra_avg']['composite']}")

    # ---- Conclusion ----
    conclusion = (
        f"Expert audit evaluated 12 Unbox-pipeline hypotheses (5 judge personas). "
        f"6 of these correspond to the Unbox hypotheses in the blinded comparison set "
        f"(IDs: {', '.join(unbox_ids)}). The 6 SCAM hypotheses ({', '.join(scam_ids)}) "
        f"were not part of the expert audit and thus lack audit scores. "
        f"Selected Unbox avg composite: {unbox_avg['composite']:.3f}, "
        f"additional Unbox avg composite: {extra_avg['composite']:.3f}, "
        f"overall audit avg composite: {all_audit_avg['composite']:.3f}. "
        f"Novelty ranged from {min(s['novelty'] for s in unbox_scores):.1f} to "
        f"{max(s['novelty'] for s in unbox_scores):.1f} (mean {unbox_avg['novelty']:.2f}). "
        f"Impact ranged from {min(s['impact'] for s in unbox_scores):.1f} to "
        f"{max(s['impact'] for s in unbox_scores):.1f} (mean {unbox_avg['impact']:.2f}). "
        f"A direct Unbox-vs-SCAM comparison requires evaluating SCAM hypotheses "
        f"through the same expert audit protocol."
    )

    print(f"\nConclusion: {conclusion}")

    # ---- Build output ----
    output = {
        "completed_at": datetime.now(timezone.utc).isoformat(),
        "methodology_note": (
            "The expert audit (expert_audit.json) evaluated 12 hypotheses all from the "
            "Unbox pipeline. The blinded comparison set (audit_blinded_set.json) contains "
            "6 Unbox + 6 SCAM hypotheses. Only the 6 Unbox hypotheses could be matched "
            "to audit evaluations. SCAM hypotheses were not evaluated in this audit."
        ),
        "unbox_hypotheses": unbox_ids,
        "scam_hypotheses": scam_ids,
        "unbox_avg": unbox_avg,
        "scam_avg": {m: None for m in METRICS},
        "delta": {m: None for m in METRICS},
        "mann_whitney_p": {m: None for m in METRICS},
        "note_on_comparison": (
            "Direct Unbox-vs-SCAM comparison not possible: SCAM hypotheses lack expert "
            "audit scores. Below we report within-Unbox analysis (selected vs additional)."
        ),
        "within_unbox_comparison": {
            "selected_avg": unbox_avg,
            "additional_avg": extra_avg,
            "all_12_avg": all_audit_avg,
            "mann_whitney_selected_vs_additional": {
                m: mw_selected_vs_extra[m] for m in METRICS
            },
        },
        "per_hypothesis_scores": per_hypothesis,
        "additional_unbox_scores": extra_per_hypothesis,
        "per_paradigm_breakdown": per_paradigm,
        "conclusion": conclusion,
    }

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nResults saved to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
