#!/usr/bin/env python3
"""Automated expert evaluation of prospective hypotheses using LLM-as-judge."""

from __future__ import annotations

import importlib
import json
import os
import sys
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import cast

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

MODEL = "claude-sonnet-4-20250514"

JUDGE_PROMPT = """You are a senior AI researcher reviewing a set of novel research hypotheses generated by an automated system. For each hypothesis, provide an independent assessment.

Rate each hypothesis on four dimensions (1-10 scale):
- novelty: How genuinely new is this idea? (1=well-known, 10=never proposed)
- feasibility: Could this be tested within 1-2 years by a small team? (1=impossible, 10=straightforward)
- impact: If validated, how significant would the contribution be? (1=trivial, 10=paradigm-shifting)
- clarity: Is the hypothesis well-defined enough to design experiments? (1=vague, 10=precise)

Also provide a brief (1-2 sentence) justification for your overall assessment.

Hypotheses to evaluate:
{hypotheses_text}

Return JSON only:
{{"evaluations": [
  {{
    "hypothesis_index": 0,
    "novelty": 1-10,
    "feasibility": 1-10,
    "impact": 1-10,
    "clarity": 1-10,
    "justification": "brief assessment"
  }}
]}}"""


def _call_judge(prompt: str, api_key: str) -> dict[str, object]:
    anthropic = importlib.import_module("anthropic")
    client = anthropic.Anthropic(api_key=api_key)

    message = None
    for attempt in range(1, 4):
        try:
            message = client.messages.create(
                model=MODEL,
                max_tokens=4096,
                messages=[{"role": "user", "content": prompt}],
            )
            break
        except Exception:
            if attempt == 3:
                raise
            time.sleep(5 * attempt)

    if message is None:
        raise RuntimeError("Judge call failed")

    text = getattr(getattr(message, "content", [None])[0], "text", "")
    decoder = json.JSONDecoder()
    for idx, ch in enumerate(text):
        if ch != "{":
            continue
        try:
            parsed, _ = decoder.raw_decode(text[idx:])
        except json.JSONDecodeError:
            continue
        if isinstance(parsed, dict):
            return cast(dict[str, object], parsed)
    raise ValueError(f"Could not parse judge JSON: {text[:300]}")


def evaluate_batch(
    hypotheses: list[dict[str, object]], api_key: str
) -> list[dict[str, object]]:
    text_parts = []
    for i, h in enumerate(hypotheses):
        text_parts.append(
            f"[{i}] Paradigm: {h.get('paradigm', 'unknown')}\n"
            f"    Original assumption: {h.get('original_assumption', '')}\n"
            f"    Transformation: {h.get('transformation', '')}\n"
            f"    Hypothesis: {h.get('hypothesis', '')}\n"
            f"    Rationale: {h.get('rationale', '')}"
        )
    hypotheses_text = "\n\n".join(text_parts)
    prompt = JUDGE_PROMPT.format(hypotheses_text=hypotheses_text)
    result = _call_judge(prompt, api_key)
    evaluations = result.get("evaluations", [])
    if not isinstance(evaluations, list):
        return []

    output = []
    for ev in evaluations:
        if not isinstance(ev, dict):
            continue
        idx = int(ev.get("hypothesis_index", -1))
        if 0 <= idx < len(hypotheses):
            merged = {**hypotheses[idx], **ev}
            n = float(ev.get("novelty", 5))
            f = float(ev.get("feasibility", 5))
            imp = float(ev.get("impact", 5))
            cl = float(ev.get("clarity", 5))
            merged["judge_composite"] = round((n + f + imp + cl) / 4, 2)
            output.append(merged)
    return output


def main() -> None:
    api_key = os.getenv("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise SystemExit("ANTHROPIC_API_KEY required")

    summary_path = PROJECT_ROOT / "experiments" / "prospective" / "summary.json"
    if not summary_path.exists():
        raise SystemExit("Run run_prospective.py first")

    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    top_hypotheses = cast(list[dict[str, object]], summary.get("top_12_hypotheses", []))

    if not top_hypotheses:
        raise SystemExit("No hypotheses to evaluate")

    print(f"Evaluating {len(top_hypotheses)} top hypotheses with LLM judge...")
    evaluated = evaluate_batch(top_hypotheses, api_key)

    def _safe_float(v: object) -> float:
        if isinstance(v, (int, float)):
            return float(v)
        return 0.0

    evaluated.sort(key=lambda x: _safe_float(x.get("judge_composite", 0)), reverse=True)

    dims = ["novelty", "feasibility", "impact", "clarity"]
    avgs: dict[str, float] = {}
    for dim in dims:
        vals = [_safe_float(e.get(dim, 0)) for e in evaluated]
        avgs[dim] = round(sum(vals) / len(vals), 2) if vals else 0.0
    avgs["judge_composite"] = round(sum(avgs.values()) / len(avgs), 2)

    output = {
        "ran_at": datetime.now(UTC).isoformat(),
        "num_evaluated": len(evaluated),
        "average_scores": avgs,
        "evaluations": evaluated,
    }

    out_path = PROJECT_ROOT / "experiments" / "prospective" / "evaluation.json"
    out_path.write_text(json.dumps(output, indent=2), encoding="utf-8")

    print(f"\nAverage scores across {len(evaluated)} hypotheses:")
    for dim, val in avgs.items():
        print(f"  {dim}: {val}")
    print(f"\nTop 5 hypotheses:")
    for i, e in enumerate(evaluated[:5], 1):
        print(
            f"  {i}. [{e.get('judge_composite', 0)}] {str(e.get('hypothesis', ''))[:90]}"
        )
    print(f"\nWrote: {out_path}")


if __name__ == "__main__":
    main()
